on: push

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup pre-requisites
        run: |
          chmod +x ./*.sh
          ./deps.sh
          ./package.sh
      - uses: jiro4989/build-deb-action@v2
        with:
          package: wireguard
          package_root: .debpkg
          maintainer: UnnoTed
          version: ${{ github.ref }}-amd64 # refs/tags/v*.*.*
          arch: 'amd64'
      - uses: jiro4989/build-deb-action@v2
        with:
          package: wireguard
          package_root: .debpkg
          maintainer: UnnoTed
          version: ${{ github.ref }}-aarch64 # refs/tags/v*.*.*
          arch: 'aarch64'
